[workflow]
workflow_schedule_interval = "@daily"
sequential_queue = "sequential"
default_queue = "general"

[files]
s3_bucket = "de300-lily-bucket"
s3_file_key = "heart_disease(in).csv"


[ml]
train_test_ratio = 0.2
outliers_std_factor = 3
labels = "HeartDisease"
tolerance = 0.01
perturbation_std = 1.2
max_perturbation_iterations = 50
confidence_level = 0.95
